add_lunch_combo lineage_hero2lte-eng
add_lunch_combo lineage_hero2lte-userdebug
add_lunch_combo lineage_hero2lte-user

add_lunch_combo aicp_hero2lte-eng
add_lunch_combo aicp_hero2lte-userdebug
add_lunch_combo aicp_hero2lte-user

add_lunch_combo aokp_hero2lte-eng
add_lunch_combo aokp_hero2lte-userdebug
add_lunch_combo aokp_hero2lte-user

add_lunch_combo aosp_hero2lte-eng
add_lunch_combo aosp_hero2lte-userdebug
add_lunch_combo aosp_hero2lte-user

add_lunch_combo gzosp_hero2lte-eng
add_lunch_combo gzosp_hero2lte-userdebug
add_lunch_combo gzosp_hero2lte-user

add_lunch_combo omni_hero2lte-eng
add_lunch_combo omni_hero2lte-userdebug
add_lunch_combo omni_hero2lte-user

add_lunch_combo rr_hero2lte-eng
add_lunch_combo rr_hero2lte-userdebug
add_lunch_combo rr_hero2lte-user
